bower.json
demo/index.html
index.html
paper-tab.html
paper-tabs-icons.html
paper-tabs.html
test/attr-for-selected.html
test/basic.html
test/index.html

/cc @notwaldorf @justinfagnani

Update for PolymerElements.

---

paper-tab.html
paper-tabs.html

Remove trackstart event handler
Fix scroll handler name to _scroll

Use 0.9 down/up gestures

---

demo/index.html

Also changed core-selected to iron-selected

Changed core-toolbar references to paper-toolbar

---

bower.json
paper-tab.html
paper-tabs.html
test/basic.html

- Applies IronMenubarBehavior
- Has appropriate ARIA role (tablist)
- Responds well to keyboard input
- Styles updated for tri-state handling of focused and selected
/cc @notwaldorf @blasten

Improve a11y for paper-tabs

---

bower.json
demo/index.html
paper-tabs.html
test/basic.html

- Replace placeholder arrow buttons with paper-icon-button
- Fix issue coordinating iron-selectable selection / deselection that
caused slider to not animate.
- Misc. doc cleanup.
Addresses #13 and #16.
/cc @morethanreal @notwaldorf

Fixes arrow buttons and slider animations

---

paper-tabs.html
test/basic.html

Make sure NaN is not cached for bar position.

---

bower.json
paper-tab.html
test/basic.html

This fixes the issue where `paper-tabs` doesn't select a tab from keyboard interaction (pressing `enter` or `space`).
/cc @tjsavage

Paper-tab is a button.

---

paper-tabs.html

Scrolling Tabs

---

bower.json
paper-tab.html
paper-tabs.html
test/basic.html

Fixes #60: Replaces `<paper-ripple>` use with `PaperRippleBehavior`.

---

demo/paper-tabs-demo-styles.html

Follow up for #80: Higher contrast for the demo.

---

paper-tabs.html

Remove extra extra curly bracket

---

paper-tab.html

Fixes #105: Removes ripple customization.

---

paper-tab.html

Applies `--paper-font-common-base` to the host.
This is part of the effort of applying `Roboto` font to all the paper elements http://jsbin.com/mumovix/1/edit?html,output

apply --paper-font-common-base

---

paper-tabs.html

Improve the `tap-highlight-color` and move external `@applys()` to top

Improve the `tap-highlight-color`

---

paper-tabs.html

This hook exist but isn't documented.

Documented Style hook

---

paper-tab.html
paper-tabs.html

Fixes https://github.com/PolymerElements/paper-tabs/issues/145

vertically align tabs

---

.travis.yml
demo/index.html
paper-tabs.html
test/basic.html

Fixes #96: Tabs activate automatically after a keypress and delay.

---

paper-tabs.html

Fixes cases where the bar animates between states with and without a selection.

---

.gitignore
.travis.yml
README.md
bower.json
demo/index.html
paper-tab.html
paper-tabs.html
test/attr-for-selected.html
test/basic.html
test/index.html
test/links.html

DO NOT MERGE
[?w=1](https://github.com/PolymerElements/paper-tabs/pull/184/files?w=1)

2.0-preview branch

---

paper-tabs.html

use :dir instead of :host-context
